apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders-api.fullname" . }}-secret
  labels:
    {{- include "orders-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ordersDb: {{ .Values.secrets.connectionStrings.ordersDb | quote }}
  rabbitmq-host: {{ .Values.secrets.rabbitmq.host | quote }}
  rabbitmq-user: {{ .Values.secrets.rabbitmq.user | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password | quote }}
  keycloak-authority: {{ .Values.secrets.keycloak.authority | quote }}

